// User Information
export interface UserInfo {
  fullName: string;
  dateOfBirth: string;
  phone: string;
  email?: string;
  address: string;
}

// Phone Verification
export interface PhoneVerification {
  isVerified: boolean;
  otpSent: boolean;
  otpCode: string;
  attempts: number;
  carrierInfo: string;
}

// Document Data
export interface DocumentData {
  type: 'passport' | 'aadhar' | 'license' | 'utility' | 'national_id' | null;
  capturedImage: string | null;
  ocrExtraction: OCRExtraction | null;
  isConfirmed: boolean;
  captureAttempts: number;
}

export interface OCRExtraction {
  documentNumber: string;
  firstName: string;
  lastName: string;
  dateOfBirth: string;
  issueDate: string;
  expiryDate: string;
  country: string;
  confidence: number;
  fields: Record<string, string>;
}

// Biometric Data
export interface BiometricData {
  selfieImage: string | null;
  faceMatchScore: number;
  livenessDetected: boolean;
  deepfakeDetected: boolean;
  pulseDetected: boolean;
  depthMapVerified: boolean;
  activeSteps: {
    headTurn: boolean;
    blink: boolean;
    smile: boolean;
  };
}

// GPS Data
export interface GPSData {
  latitude: number | null;
  longitude: number | null;
  address: string | null;
  isMatched: boolean;
  matchConfidence: number;
}

// Risk Assessment
export interface RiskAssessment {
  documentAuthenticity: number;
  faceMatchScore: number;
  gpsMatch: number;
  phoneVerification: number;
  systemRiskScore: number;
  riskLevel: 'green' | 'amber' | 'red';
  factors: RiskFactor[];
  explanation: string;
}

export interface RiskFactor {
  name: string;
  score: number;
  impact: 'low' | 'medium' | 'high';
  description: string;
}

// KYC Session - Represents a single customer's KYC process
export interface KYCSession {
  id: string;
  organizationId: string;  // KEY: Links to organization
  customerId?: string;     // NEW: Customer being verified
  invitationId?: string;   // NEW: From invitation link
  status: 'pending' | 'approved' | 'rejected' | 'needs_review' | 'submitted';
  currentStep: number;
  userInfo: UserInfo | null;
  phoneVerification: PhoneVerification | null;
  document: DocumentData | null;
  biometric: BiometricData | null;
  gps: GPSData | null;
  riskAssessment: RiskAssessment | null;
  createdAt: Date;
  updatedAt: Date;
  submittedAt?: Date;      // NEW: When customer completed
  reviewedAt?: Date;       // NEW: When org reviewed
  reviewedBy?: string;     // NEW: Which org user reviewed
  notes?: string;          // NEW: Org review notes
  result?: KYCResult;
}

export interface KYCResult {
  status: 'approved' | 'rejected' | 'needs_review';
  score: number;
  reasons: string[];
  recommendations: string[];
  reviewedBy?: string;
  reviewedAt?: Date;
}

// Languages
export type Language = {
  code: string;
  name: string;
  nativeName: string;
};

// Document Types
export interface DocumentType {
  id: string;
  name: string;
  description: string;
  icon: string;
  countries: string[];
  validityYears: number;
}

// NEW: KYC Invitation Link (Generated by Organization)
export interface KYCInvitation {
  id: string;
  organizationId: string;
  code: string;                           // Unique code (e.g., ABC123XYZ)
  name?: string;                          // Optional: Link name/label
  expiresAt: Date;
  createdAt: Date;
  usageLimit?: number;                    // Max customers who can use this link
  usageCount: number;                     // How many have used it
  isActive: boolean;
  shareUrl?: string;                      // Full URL to share: /kyc/invite/{code}
  createdBy: string;                      // Org user who created
  requiredDocuments?: string[];
  customBranding?: {
    logoUrl?: string;
    primaryColor?: string;
    companyName?: string;
  }
}

// NEW: Customer Submission (Result of KYC process)
export interface CustomerSubmission {
  id: string;
  organizationId: string;
  invitationId: string;
  kycSessionId: string;
  customerEmail?: string;
  customerName?: string;
  customerPhone?: string;
  status: 'submitted' | 'approved' | 'rejected' | 'needs_review' | 'archived';
  submittedAt: Date;
  reviewedAt?: Date;
  reviewedBy?: string;                    // Org user who reviewed
  notes?: string;
  riskScore?: number;
  riskLevel?: 'green' | 'amber' | 'red';
  sourceIp?: string;
  sourceLocation?: string;
}

// NEW: Customer-facing user type (temporary, for KYC submission)
export interface Customer {
  id: string;
  organizationId: string;
  email?: string;
  name?: string;
  phone?: string;
  invitationCode: string;
  sessionId: string;
  startedAt: Date;
  completedAt?: Date;
  ipAddress?: string;
}

